import type { NextPage } from "next";
import {
  Button,
  Flex,
  Heading,
  Input,
  useColorMode,
  useColorModeValue,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Login: NextPage = () => {
  const { toggleColorMode } = useColorMode();
  const formBg = useColorModeValue("gray.200", "gray.700");
  return (
    <Flex height="100vh" alignItems="center" justifyContent="center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="column" background={formBg} p={12} rounded={6}>
        <Heading mb={6}>Log in</Heading>
        <Input
          placeholder="example@johndoe.com"
          variant="outline"
          mb={3}
          type="email"
          size="lg"
        />
        <Input
          placeholder="************"
          variant="outline"
          mb={6}
          type="password"
          size="lg"
        />
        <Button colorScheme="green" mb={6}>
          Log in
        </Button>
        <Link href={"/"}>
          <a>Back to home</a>
        </Link>
        <Button onClick={toggleColorMode}>Toggle Color</Button>
      </Flex>
    </Flex>
  );
};

export default Login;
